http:
  ip:              127.0.0.1
  host:            localhost
  port:            3000
  read_timeout:    30  # Seconds
  write_timeout:   30  # Seconds

postgresql:
  username:           postgres           #myuser            #postgres
  password:           GCvhFTduk1         #1                 #GCvhFTduk1
  host:               localhost          #rdbms.vt          #localhost
  port:               5432
  database:           hospital           #hospital_server   #hospital
  request_timeout:    5                  # Seconds
  connection_timeout: 10                 # Seconds
  shutdown_timeout:   5                  # Seconds